### ISSUE TITLE
Can I include this project in a Makie blogpost?

### ISSUE THREAD

**Issue by SimonDanisch** [bradcarman/ModelingToolkitDesigner.jl#4]
Hi,
I love this project and would like to know more about it - and actually include it in a blogpost, which shows off new, exciting packages using Makie.
Hope its okay, that I already mention it in my MakieCon talk - I just couldn't resist: https://youtu.be/9L4G1Wyq8kw?t=1020

Would love to chat on slack/linkedin, but haven't managed to reach out there yet ;) 

Best,
Simon

**Comment by bradcarman** [comment]
Hi Simon- I’d be honored!  Feel free to reach out to me, email/handle is bradleygcarman at gmail and twitter
